# ==========================================================
# Kubernetes ConfigMap
# File      : config-map-common.yaml
# Project   : MSIMPL - Microservices Platform
# Author    : Sanjeev Kumar
#
# Description
# -----------
# Stores common, non-sensitive configuration shared across
# all MSIMPL microservices.
#
# Purpose
# -------
# - Common Spring Boot configuration
# - Active Spring profile
# - Default logging level
#
# Notes
# -----
# - Do NOT store passwords, API keys or tokens.
# - Sensitive values must be stored in Kubernetes Secrets.
# - Kafka, Database and Observability configurations are
#   maintained in their respective ConfigMaps.
#
# ==========================================================

apiVersion: v1
kind: ConfigMap

metadata:
  name: msimpl-common-config
  namespace: msimpl

  labels:
    app.kubernetes.io/name: msimpl
    app.kubernetes.io/component: common-config
    app.kubernetes.io/part-of: microservices-platform

data:

  # --------------------------------------------------------
  # Spring Boot
  # --------------------------------------------------------
  SPRING_PROFILES_ACTIVE: "docker"

  # --------------------------------------------------------
  # Logging
  # --------------------------------------------------------
  LOG_LEVEL_ROOT: "INFO"