# ==========================================================
# Kubernetes Secret
# File      : secret.yaml
# Project   : MSIMPL - Microservices Platform
# Author    : Sanjeev Kumar
#
# Description
# -----------
# Stores sensitive configuration shared across MSIMPL
# microservices.
#
# Purpose
# -------
# - Database Credentials
#
# Notes
# -----
# - Do NOT store non-sensitive configuration here.
# - Database host, port and database name belong to
#   config-map-database.yaml.
# - Values under stringData are automatically Base64
#   encoded by Kubernetes when the Secret is created.
# - Additional secrets such as JWT, Redis and Kafka
#   credentials can be added later.
#
# ==========================================================

apiVersion: v1
kind: Secret

metadata:
  name: msimpl-secret
  namespace: msimpl

  labels:
    app.kubernetes.io/name: msimpl
    app.kubernetes.io/component: application-secret
    app.kubernetes.io/part-of: microservices-platform

type: Opaque

stringData:

  # --------------------------------------------------------
  # Database Credentials
  # --------------------------------------------------------
  DB_USERNAME: "postgres"

  DB_PASSWORD: "postgres"