name: Hello MSIMPL

on:
  push:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Welcome Message
        run: echo "Hello MSIMPL! My first GitHub Action is running successfully."