name: Orchestrator_Workflow

on:
  push:
    branches:
      - main
    paths:
      - "ms-transaction-orchestrator/**"
      - ".github/workflows/ms-transaction-orchestrator-ci.yml"

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Welcome Message
        run: echo "Hello Orchestrator_Workflow! My Orchestrator_Workflow GitHub Action is running successfully."